name: ttig
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip>=20
  - pytorch>=1.10
  - torchvision
  - transformers
  - datasets
  - kornia
  - torch-optimizer
  - numpy
  - pyarrow
  - opencv
  - pytest
  - pip:
    - ./clean-fid
    - ./vqgan-clip
    - ./CLIP
    - taming-transformers==0.0.1
    - albumentations==0.4.3
    - pudb==2019.2
    - pytorch-lightning==1.0.8
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.0.0
    - test-tube>=0.7.5
    - einops==0.3.0
    - more-itertools>=8.0.0
    - torchtyping
    - typeguard
    - typer
    - webdataset
    - tqdm
