name: timm
channels:
  - pytorch
  - moasaicml
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip>=22
  - pytorch>=1.10
  - torchvision
  - mosaicml
  - pip:
    - braceexpand
    - omegaconf
    - polars
    - timm
    - tqdm
    - wandb
    - webdatasets
