data_dir: '/mnt/ssd-dashiell/imagenet/ILSVRC/Data/CLS-LOC/'
model: 'inception_v3'
aa: "rand-m9-mstd0.5-inc1"
sched: cosine
batch_size: 64
color_jitter: 0.4
aug_splits: 3
cooldown_epochs: 10
lr: 0.05
epochs: 200
amp: true
remode: pixel
resplit: true
split_bn: true
jst: true
dist_bn: reduce
reprob: 0.6

